### ISSUE TITLE
Añadir control para verificar que los nodos son objetos/instancias diferentes

### ISSUE THREAD

**Issue by jordaninsfran** [Grupo-de-Computacion-de-la-FI-UNER/ayed-tps-codigos-iniciales-para-estudiantes#3]
https://github.com/Grupo-de-Computacion-de-la-FI-UNER/ayed-tps-codigos-iniciales-para-estudiantes/blob/40b2238ea61146447b80c460c3f8dcc21dbb1a14/2022_TP1_LDE_testing/test_LDE.py#L210

Propongo añadir la siguiente línea al test, luego de la línea indicada en el asunto:
```python
self.assertNotEqual(id(nodo_original), id(nodo_copia))
```
La idea es verificar que los nodos son objetos/instancias diferentes.

**Comment by BrunoBreggia-FIUNER** [comment]
Resuelto

**Comment by jordaninsfran** [comment]
No observo la resolución. Podrían referirme a la línea de código/rama donde se encuentra?
Gracias desde ahora.

**Comment by BrunoBreggia-FIUNER** [comment]
La verificación esta se realiza en el test test_copiar, en dos oportunidades:
1. Para verificar que el objeto LDE copiado sea diferente al original...
https://github.com/Grupo-de-Computacion-de-la-FI-UNER/ayed-tps-codigos-iniciales-para-estudiantes/blob/c63a1e3f9e4bd8bf9afc7f063f3437ad38354f15/TP1_LDE_testing/test_LDE.py#L309

2. Para verificar que cada uno de los nodos copiados sean en memoria objetos distintos a los de la lista original...
https://github.com/Grupo-de-Computacion-de-la-FI-UNER/ayed-tps-codigos-iniciales-para-estudiantes/blob/c63a1e3f9e4bd8bf9afc7f063f3437ad38354f15/TP1_LDE_testing/test_LDE.py#L317

Por esto mismo doy por resuelto el presente issue.
P/D: el issue original referencia a un metodo auxiliar del test para copiar listas, el cual fue eliminado. El contenido de este metodo se volcó íntegramente a test_copiar, por considerar mejor contener toda la lógica del testeo de la copia en un único lugar.

**Comment by BrunoBreggia-FIUNER** [comment]
Acabo de notar un error en la linea 309, ahora ha sido corregida.

https://github.com/Grupo-de-Computacion-de-la-FI-UNER/ayed-tps-codigos-iniciales-para-estudiantes/blob/74fdd8fae8e47e80245db395b4010aa9512f6ce2/TP1_LDE_testing/test_LDE.py#L309

P/D: ahora sí considero resuelto el presento issue
