### ISSUE TITLE
Actualizar nombre del test.

### ISSUE THREAD

**Issue by jordaninsfran** [Grupo-de-Computacion-de-la-FI-UNER/ayed-tps-codigos-iniciales-para-estudiantes#5]
https://github.com/Grupo-de-Computacion-de-la-FI-UNER/ayed-tps-codigos-iniciales-para-estudiantes/blob/40b2238ea61146447b80c460c3f8dcc21dbb1a14/2022_TP1_LDE_testing/test_LDE.py#L48

El nombre del test debería pasar a ser "test_agregar_al_inicio" o similar.

**Comment by belferster** [comment]
Resuelto
