### ISSUE TITLE
Añadir control del tamaño de la LDE antes y después de agregar al final el item. Debería haber aumentado en 1 el tamaño.

### ISSUE THREAD

**Issue by jordaninsfran** [Grupo-de-Computacion-de-la-FI-UNER/ayed-tps-codigos-iniciales-para-estudiantes#8]
https://github.com/Grupo-de-Computacion-de-la-FI-UNER/ayed-tps-codigos-iniciales-para-estudiantes/blob/40b2238ea61146447b80c460c3f8dcc21dbb1a14/2022_TP1_LDE_testing/test_LDE.py#L64

**Comment by BrunoBreggia-FIUNER** [comment]
Resuelto
