### ISSUE TITLE
Añadir verificación al final para asegurarse que nodo_inicio y nodo_fin poseen el valor None.

### ISSUE THREAD

**Issue by jordaninsfran** [Grupo-de-Computacion-de-la-FI-UNER/ayed-tps-codigos-iniciales-para-estudiantes#9]
https://github.com/Grupo-de-Computacion-de-la-FI-UNER/ayed-tps-codigos-iniciales-para-estudiantes/blob/40b2238ea61146447b80c460c3f8dcc21dbb1a14/2022_TP1_LDE_testing/test_LDE.py#L249

Añadir al final del test una aserción que verifique que los nodos "nodo_inicio" y "nodo_fin" poseen el valor **None** luego del último bucle.

Esto permitirá verificar que el nodo sucesor del último nodo de la lista original es None, y que el antecesor del primer nodo de la lista invertida es None.

**Comment by BrunoBreggia-FIUNER** [comment]
Resuelto

**Comment by jordaninsfran** [comment]
No consigo observar la resolución. Por favor, referir la línea/s de código donde se resolvió.
